/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusesRouteImport } from './routes/bonuses'
import { Route as BonusesIndexRouteImport } from './routes/bonuses/index'
import { Route as BonusesBonusIdRouteImport } from './routes/bonuses/$bonusId'
import { Route as ApiTelegramChatsRouteImport } from './routes/api.telegram.chats'
import { Route as ApiTelegramTestRouteImport } from './routes/api.telegram.test'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesRoute = BonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesIndexRoute = BonusesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BonusesRoute,
} as any)
const BonusesBonusIdRoute = BonusesBonusIdRouteImport.update({
  id: '/$bonusId',
  path: '/$bonusId',
  getParentRoute: () => BonusesRoute,
} as any)
const ApiTelegramChatsRoute = ApiTelegramChatsRouteImport.update({
  id: '/api/telegram/chats',
  path: '/api/telegram/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramTestRoute = ApiTelegramTestRouteImport.update({
  id: '/api/telegram/test',
  path: '/api/telegram/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonuses': typeof BonusesRouteWithChildren
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses/': typeof BonusesIndexRoute
  '/api/telegram/chats': typeof ApiTelegramChatsRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses': typeof BonusesIndexRoute
  '/api/telegram/chats': typeof ApiTelegramChatsRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonuses': typeof BonusesRouteWithChildren
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses/': typeof BonusesIndexRoute
  '/api/telegram/chats': typeof ApiTelegramChatsRoute
  '/api/telegram/test': typeof ApiTelegramTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bonuses'
    | '/bonuses/$bonusId'
    | '/bonuses/'
    | '/api/telegram/chats'
    | '/api/telegram/test'
    | '/api/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bonuses/$bonusId'
    | '/bonuses'
    | '/api/telegram/chats'
    | '/api/telegram/test'
    | '/api/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/bonuses'
    | '/bonuses/$bonusId'
    | '/bonuses/'
    | '/api/telegram/chats'
    | '/api/telegram/test'
    | '/api/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusesRoute: typeof BonusesRouteWithChildren
  ApiTelegramChatsRoute: typeof ApiTelegramChatsRoute
  ApiTelegramTestRoute: typeof ApiTelegramTestRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses': {
      id: '/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof BonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses/': {
      id: '/bonuses/'
      path: '/'
      fullPath: '/bonuses/'
      preLoaderRoute: typeof BonusesIndexRouteImport
      parentRoute: typeof BonusesRoute
    }
    '/bonuses/$bonusId': {
      id: '/bonuses/$bonusId'
      path: '/$bonusId'
      fullPath: '/bonuses/$bonusId'
      preLoaderRoute: typeof BonusesBonusIdRouteImport
      parentRoute: typeof BonusesRoute
    }
    '/api/telegram/chats': {
      id: '/api/telegram/chats'
      path: '/api/telegram/chats'
      fullPath: '/api/telegram/chats'
      preLoaderRoute: typeof ApiTelegramChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/test': {
      id: '/api/telegram/test'
      path: '/api/telegram/test'
      fullPath: '/api/telegram/test'
      preLoaderRoute: typeof ApiTelegramTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BonusesRouteChildren {
  BonusesBonusIdRoute: typeof BonusesBonusIdRoute
  BonusesIndexRoute: typeof BonusesIndexRoute
}

const BonusesRouteChildren: BonusesRouteChildren = {
  BonusesBonusIdRoute: BonusesBonusIdRoute,
  BonusesIndexRoute: BonusesIndexRoute,
}

const BonusesRouteWithChildren =
  BonusesRoute._addFileChildren(BonusesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusesRoute: BonusesRouteWithChildren,
  ApiTelegramChatsRoute: ApiTelegramChatsRoute,
  ApiTelegramTestRoute: ApiTelegramTestRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
