/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BonusesRouteImport } from './routes/bonuses'
import { Route as BonusesIndexRouteImport } from './routes/bonuses/index'
import { Route as BonusesBonusIdRouteImport } from './routes/bonuses/$bonusId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesRoute = BonusesRouteImport.update({
  id: '/bonuses',
  path: '/bonuses',
  getParentRoute: () => rootRouteImport,
} as any)
const BonusesIndexRoute = BonusesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BonusesRoute,
} as any)
const BonusesBonusIdRoute = BonusesBonusIdRouteImport.update({
  id: '/$bonusId',
  path: '/$bonusId',
  getParentRoute: () => BonusesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bonuses': typeof BonusesRouteWithChildren
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses/': typeof BonusesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses': typeof BonusesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bonuses': typeof BonusesRouteWithChildren
  '/bonuses/$bonusId': typeof BonusesBonusIdRoute
  '/bonuses/': typeof BonusesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bonuses' | '/bonuses/$bonusId' | '/bonuses/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bonuses/$bonusId' | '/bonuses'
  id: '__root__' | '/' | '/bonuses' | '/bonuses/$bonusId' | '/bonuses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BonusesRoute: typeof BonusesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses': {
      id: '/bonuses'
      path: '/bonuses'
      fullPath: '/bonuses'
      preLoaderRoute: typeof BonusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bonuses/': {
      id: '/bonuses/'
      path: '/'
      fullPath: '/bonuses/'
      preLoaderRoute: typeof BonusesIndexRouteImport
      parentRoute: typeof BonusesRoute
    }
    '/bonuses/$bonusId': {
      id: '/bonuses/$bonusId'
      path: '/$bonusId'
      fullPath: '/bonuses/$bonusId'
      preLoaderRoute: typeof BonusesBonusIdRouteImport
      parentRoute: typeof BonusesRoute
    }
  }
}

interface BonusesRouteChildren {
  BonusesBonusIdRoute: typeof BonusesBonusIdRoute
  BonusesIndexRoute: typeof BonusesIndexRoute
}

const BonusesRouteChildren: BonusesRouteChildren = {
  BonusesBonusIdRoute: BonusesBonusIdRoute,
  BonusesIndexRoute: BonusesIndexRoute,
}

const BonusesRouteWithChildren =
  BonusesRoute._addFileChildren(BonusesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BonusesRoute: BonusesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
